package com.geminx.mod;

/**
 * ItemData.java - Auto-generated item database
 * Format: {{id, "Nama Item"}}
 * Generated by generate_java.py
 */
public class ItemData {

    // ── Sayuran & Buah ───────────────────────────────
    public static final Object[][] FOOD_SAYURAN = {
        {1, "Kentang"},  // Item_Name_1
        {2, "Jagung"},  // Item_Name_2
        {3, "Gandum"},  // Item_Name_3
        {4, "gandum"},  // Item_Name_4
        {5, "Beras"},  // Item_Name_5
        {101, "Sayuran Liar"},  // Item_Name_101
        {102, "Bawang bombai"},  // Item_Name_102
        {103, "Jamur"},  // Item_Name_103
        {105, "Brokoli"},  // Item_Name_105
        {106, "Cabai"},  // Item_Name_106
        {107, "Labu kuning"},  // Item_Name_107
        {108, "Kubis"},  // Item_Name_108
        {110, "Labu"},  // Item_Name_110
        {111, "Selada"},  // Item_Name_111
        {112, "Tomat"},  // Item_Name_112
        {214, "Apel"},  // Item_Name_202
        {215, "Ceri"},  // Item_Name_203
        {216, "Kastanye"},  // Item_Name_204
        {217, "Persik"},  // Item_Name_205
        {218, "Pir"},  // Item_Name_206
        {219, "kacang pikan"},  // Item_Name_207
        {220, "Prem"},  // Item_Name_208
        {221, "Anggur"},  // Item_Name_209
        {222, "Tanggal"},  // Item_Name_200010
        {223, "Kaleng Sayur"},  // Item_Name_109
        {224, "Buah Kaleng"},  // Item_Name_210
        {403, "Kacang polong"},  // Item_Name_403
        {404, "Kedelai"},  // Item_Name_404
        {405, "buncis"},  // Item_Name_405
        {7018, "Anggur"},  // Item_Name_80004
        {200019, "Potongan Kaktus"},  // Item_Name_200019
    };

    // ── Daging & Protein ─────────────────────────────
    public static final Object[][] FOOD_DAGING = {
        {225, "Ikan Asin Kaleng"},  // Item_Name_211
        {226, "Kaleng Daging"},  // Item_Name_212
        {301, "Daging rusa"},  // Item_Name_301
        {303, "Daging domba"},  // Item_Name_303
        {304, "Daging sapi"},  // Item_Name_304
        {308, "Daging Alpaka"},  // Item_Name_308
        {309, "Daging Kerbau"},  // Item_Name_309
        {314, "Daging Kuda"},  // Item_Name_314
        {315, "Daging Keledai"},  // Item_Name_315
        {316, "Potongan Daging"},  // Item_Name_316
        {326, "Lobster"},  // Item_Name_326
        {334, "Telur"},  // Item_Name_302
        {335, "Susu"},  // Item_Name_311
        {401, "Ikan"},  // Item_Name_401
        {402, "Ikan Asin"},  // Item_Name_402
        {200007, "Tiram"},  // Item_Name_200007
    };

    // ── Olahan & Masakan ─────────────────────────────
    public static final Object[][] FOOD_OLAHAN = {
        {7, "Tepung"},  // Item_Name_7
        {8, "Roti panggang"},  // Item_Name_8
        {9, "kue"},  // Item_Name_9
        {10, "croissant"},  // Item_Name_10
        {13, "Kue Buah"},  // Item_Name_13
        {14, "pai buah"},  // Item_Name_14
        {15, "Kelezatan"},  // Item_Name_15
        {16, "Pai"},  // Item_Name_11
        {17, "Kue"},  // Item_Name_12
        {213, "Selai"},  // Item_Name_201
        {317, "Daging Asin"},  // Item_Name_317
        {318, "Daging Asap"},  // Item_Name_318
        {319, "daging babi asap"},  // Item_Name_319
        {320, "Sosis"},  // Item_Name_320
        {321, "Ham"},  // Item_Name_321
        {322, "Dendeng Kerbau"},  // Item_Name_322
        {325, "Rak Domba"},  // Item_Name_325
        {327, "Lobster Panggang"},  // Item_Name_327
        {328, "Kelezatan"},  // Item_Name_328
        {329, "Pesta"},  // Item_Name_329
        {330, "Piknik"},  // Item_Name_330
        {331, "Salad Sayuran"},  // Item_Name_331
        {332, "Roti Petani"},  // Item_Name_332
        {333, "Roti Upacara"},  // Item_Name_333
        {336, "Steak"},  // Item_Name_323
        {337, "Kalkun panggang"},  // Item_Name_324
        {501, "Sayang"},  // Item_Name_501
        {503, "Gula"},  // Item_Name_502
        {504, "Garam"},  // Item_Name_504
        {515, "Permen Buah"},  // Item_Name_508
        {516, "Cokelat"},  // Item_Name_510
        {517, "Permen"},  // Item_Name_506
        {518, "Camilan labu"},  // Item_Name_518
        {51006, "Mentega"},  // Item_Name_51006
        {130004, "kue beras"},  // Item_Name_130004
        {130005, "pangsit"},  // Item_Name_130005
        {130006, "Puding Lem"},  // Item_Name_130006
        {200022, "Kakao Pedas"},  // Item_Name_200022
        {200023, "taco"},  // Item_Name_200023
        {200024, "jagung popcorn"},  // Item_Name_200024
        {200025, "Tahu"},  // Item_Name_200003
    };

    // ── Minuman ──────────────────────────────────────
    public static final Object[][] FOOD_MINUMAN = {
        {1001, "Air"},  // Item_Name_1001
        {7007, "Kopi"},  // Item_Name_7007
        {7008, "Kakao"},  // Item_Name_7008
        {7009, "Teh Hitam"},  // Item_Name_7009
        {7011, "Bir"},  // Item_Name_80001
        {7012, "adas manis"},  // Item_Name_200011
        {7015, "Tequila"},  // Item_Name_80005
        {7016, "Anggur Tusu"},  // Item_Name_130007
        {7017, "Wiski"},  // Item_Name_80003
    };

    // ── Tekstil & Pakaian ────────────────────────────
    public static final Object[][] RAW_TEKSTIL = {
        {6001, "Kulit"},  // Item_Name_6001
        {6002, "Wol"},  // Item_Name_6002
        {6003, "Bulu"},  // Item_Name_6003
        {6004, "Wol Alpaka"},  // Item_Name_6004
        {6005, "Lenan"},  // Item_Name_6005
        {6006, "Kapas"},  // Item_Name_6006
        {6007, "Linen"},  // Item_Name_6007
        {6008, "Kain Katun"},  // Item_Name_6008
        {6009, "Kulit Halus"},  // Item_Name_6009
        {6010, "Daun Murbei"},  // Item_Name_6010
        {6011, "Sutra"},  // Item_Name_6011
        {6012, "Kepompong Ulat Sutera"},  // Item_Name_6012
        {6013, "Segel Bulu"},  // Item_Name_6013
        {32007, "Set Tempat Tidur"},  // Item_Name_32007
        {32013, "Tempat Tidur Mewah"},  // Item_Name_32013
        {50001, "Pakaian Kasar"},  // Item_Name_50001
        {50002, "Jaket Bawah"},  // Item_Name_50002
        {50004, "Ransel"},  // Item_Name_50004
        {50005, "Straw Shoes"},  // Item_Name_50005
        {50006, "Sepatu Kulit"},  // Item_Name_50006
        {50007, "Sepatu Bot Kulit"},  // Item_Name_50007
        {50008, "Keranjang"},  // Item_Name_50008
        {50009, "Gerobak tangan"},  // Item_Name_50009
        {50010, "Kostum"},  // Item_Name_50010
        {80201, "Gaun"},  // Item_Name_80201
        {80202, "Gaun Kustom"},  // Item_Name_80202
        {200013, "Mewarnai Kain"},  // Item_Name_200013
    };

    // ── Bangunan & Material ──────────────────────────
    public static final Object[][] RAW_BANGUNAN = {
        {3001, "Kayu"},  // Item_Name_3001
        {3002, "Papan"},  // Item_Name_3002
        {4001, "Batu"},  // Item_Name_4001
        {4002, "Potong Batu"},  // Item_Name_4002
        {4003, "Giok"},  // Item_Name_4003
        {5001, "Bijih besi"},  // Item_Name_5001
        {5002, "Bijih Perak"},  // Item_Name_5002
        {5003, "Pasir Emas"},  // Item_Name_5003
        {30002, "Batu bara"},  // Item_Name_30002
        {32001, "Kaca"},  // Item_Name_32001
        {32003, "Bata"},  // Item_Name_32003
        {32004, "Baja"},  // Item_Name_32004
        {33002, "buluh"},  // Item_Name_33002
        {33004, "Botol Kaca"},  // Item_Name_33004
        {33007, "Pasir"},  // Item_Name_33007
        {33008, "Tanah liat"},  // Item_Name_33008
        {51007, "Tali"},  // Item_Name_51007
        {200002, "Bambu"},  // Item_Name_200002
        {200004, "Kayu keras"},  // Item_Name_200004
        {200020, "Obsidian"},  // Item_Name_200020
    };

    // ── Pertanian & Kimia ────────────────────────────
    public static final Object[][] RAW_PERTANIAN = {
        {6, "malt"},  // Item_Name_6
        {2003, "Minyak Obat"},  // Item_Name_2003
        {7002, "Biji Kopi"},  // Item_Name_7002
        {7003, "Tembakau"},  // Item_Name_7003
        {7004, "Teh"},  // Item_Name_7004
        {9001, "Herba"},  // Item_Name_2001
        {9002, "Jus Kaktus"},  // Item_Name_200017
        {9003, "Kedokteran Khusus"},  // Item_Name_2004
        {9006, "Sabun"},  // Item_Name_51003
        {9007, "Sabun Medis"},  // Item_Name_51011
        {9010, "Perban"},  // Item_Name_2005
        {9014, "sabun garam"},  // Item_Name_9014
        {30001, "Bahan Bakar Domestik"},  // Item_Name_30001
        {30003, "Pupuk"},  // Item_Name_30003
        {30004, "Makanan ternak"},  // Item_Name_30004
        {30005, "Kotoran Hewan Kering"},  // Item_Name_30005
        {31001, "Bahan Bakar Halus"},  // Item_Name_31001
        {33001, "lilin lebah"},  // Item_Name_33001
        {33003, "Agave"},  // Item_Name_33003
        {33005, "Gemuk"},  // Item_Name_33005
        {33006, "Lapisan lemak"},  // Item_Name_33006
        {33010, "Bit gula"},  // Item_Name_33010
        {33011, "Tebu"},  // Item_Name_33011
        {33012, "Getah Maple"},  // Item_Name_33012
        {200018, "Kaktus"},  // Item_Name_200018
    };

    // ── Alat & Peralatan ─────────────────────────────
    public static final Object[][] RAW_ALAT = {
        {9008, "Kertas"},  // Item_Name_33009
        {9009, "Buku"},  // Item_Name_33014
        {32005, "Alat bangunan susun"},  // Item_Name_32005
        {33013, "Tinta"},  // Item_Name_33013
        {51001, "Alat Batu"},  // Item_Name_51001
        {51002, "Alat Besi"},  // Item_Name_51002
        {51005, "Minyak Lampu"},  // Item_Name_51005
        {51008, "Jaring Ikan"},  // Item_Name_51008
        {51009, "Alat Baja"},  // Item_Name_51009
        {51010, "Perangkat Perkakas"},  // Item_Name_51010
        {51012, "Gigi"},  // Item_Name_51012
        {51013, "Perangkap"},  // Item_Name_51013
        {200005, "Alat Kayu Keras"},  // Item_Name_200005
        {200006, "Alat Kayu Keras yang Kokoh"},  // Item_Name_200006
        {200021, "Alat Obsidian"},  // Item_Name_200021
    };

    // ── Benih & Tanaman ──────────────────────────────
    public static final Object[][] SEED = {
        {7005, "Biji Kakao"},  // Item_Name_7005
        {101001, "Benih Kentang"},  // Item_Name_101001
        {101003, "Bibit Brokoli"},  // Item_Name_101003
        {101004, "Benih Jagung"},  // Item_Name_101004
        {101005, "Biji Cabai"},  // Item_Name_101005
        {101006, "Biji Labu"},  // Item_Name_101006
        {101007, "Biji Gandum"},  // Item_Name_101007
        {101008, "Benih Kubis"},  // Item_Name_101008
        {101009, "Biji Agave"},  // Item_Name_101009
        {101010, "Biji Rami"},  // Item_Name_101010
        {101011, "Benih Kapas"},  // Item_Name_101011
        {101012, "Biji Oat"},  // Item_Name_101012
        {101013, "Benih Padi"},  // Item_Name_101013
        {101014, "Biji Kacang"},  // Item_Name_101014
        {101015, "Benih Kedelai"},  // Item_Name_101015
        {101016, "Biji Buncis"},  // Item_Name_101016
        {101017, "Biji Labu"},  // Item_Name_101017
        {101018, "Biji Selada"},  // Item_Name_101018
        {101019, "Biji Tomat"},  // Item_Name_101019
        {101020, "Biji Bit Gula"},  // Item_Name_101020
        {101021, "Benih Tebu"},  // Item_Name_101021
        {101022, "Bibit Kopi"},  // Item_Name_101022
        {101023, "Bibit Tembakau"},  // Item_Name_101023
        {101502, "Bibit Apel"},  // Item_Name_101502
        {101503, "Biji Ceri"},  // Item_Name_101503
        {101504, "Biji Kastanye"},  // Item_Name_101504
        {101505, "Biji Persik"},  // Item_Name_101505
        {101506, "Biji Pir"},  // Item_Name_101506
        {101507, "Biji Kemiri"},  // Item_Name_101507
        {101508, "Biji Plum"},  // Item_Name_101508
        {101509, "Biji Anggur"},  // Item_Name_101509
        {101510, "Benih Maple"},  // Item_Name_101510
        {101511, "Biji Murbei"},  // Item_Name_101511
        {101512, "Biji Teh"},  // Item_Name_101512
        {101513, "Biji Kakao"},  // Item_Name_101513
        {101801, "Bibit Pohon"},  // Item_Name_101801
        {101902, "Benih Ramuan"},  // Item_Name_101902
        {200001, "Bibit Bambu"},  // Item_Name_200001
        {200008, "Benih Kayu Keras"},  // Item_Name_200008
        {200009, "Benih Kurma"},  // Item_Name_200009
        {200016, "Bibit Kaktus"},  // Item_Name_200016
    };

    // ── Hewan Ternak ─────────────────────────────────
    public static final Object[][] ANIMAL = {
        {305, "Ayam"},  // Item_Name_305
        {306, "Turki"},  // Item_Name_306
        {307, "Angsa"},  // Item_Name_307
        {312, "Bebek"},  // Item_Name_312
        {313, "Babi"},  // Item_Name_313
        {102001, "Domba"},  // Item_Name_102001
        {102002, "Sapi"},  // Item_Name_102002
        {102003, "Ayam"},  // Item_Name_102003
        {102005, "Turki"},  // Item_Name_102005
        {102006, "Angsa"},  // Item_Name_102006
        {102007, "alpaka"},  // Item_Name_102007
        {102008, "Ternak"},  // Item_Name_102008
        {102009, "Bebek"},  // Item_Name_102009
        {102010, "Babi"},  // Item_Name_102010
        {102011, "Kuda"},  // Item_Name_102011
        {102012, "Keledai"},  // Item_Name_102012
        {102013, "Ayam menganggur"},  // Item_Name_102013
        {102014, "Kerbau"},  // Item_Name_102014
    };

    // ── Semua kategori ─────────────────────────────────
    public static final String[] CATEGORY_NAMES = {
        "Sayuran & Buah",
        "Daging & Protein",
        "Olahan & Masakan",
        "Minuman",
        "Tekstil & Pakaian",
        "Bangunan & Material",
        "Pertanian & Kimia",
        "Alat & Peralatan",
        "Benih & Tanaman",
        "Hewan Ternak",
    };

    public static final Object[][][] ALL_CATEGORIES = {
        FOOD_SAYURAN,
        FOOD_DAGING,
        FOOD_OLAHAN,
        FOOD_MINUMAN,
        RAW_TEKSTIL,
        RAW_BANGUNAN,
        RAW_PERTANIAN,
        RAW_ALAT,
        SEED,
        ANIMAL,
    };

    /** Cari nama item by ID, return null kalau tidak ketemu */
    public static String getNameById(int id) {
        for (Object[][] cat : ALL_CATEGORIES) {
            for (Object[] item : cat) {
                if ((int) item[0] == id) return (String) item[1];
            }
        }
        return null;
    }
}