name: Build🔥👿🤖FlashMod APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > mod.keystore
          $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign \
            -v -p 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app-aligned.apk
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
            --ks mod.keystore \
            --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --out FlashMod-signed.apk \
            app-aligned.apk
          ls -lh FlashMod-signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FlashMod
          path: FlashMod-signed.apk
